services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: ai_sales_postgres
    environment:
      POSTGRES_DB: ai_sales_db
      POSTGRES_USER: ai_sales_user
      POSTGRES_PASSWORD: ai_sales_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../config/database/sql/init:/docker-entrypoint-initdb.d
    networks:
      - ai_sales_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_sales_user -d ai_sales_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存 (会话缓存 + Celery broker)
  redis:
    image: redis:7-alpine
    container_name: ai_sales_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_sales_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant 向量数据库
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: ai_sales_qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    networks:
      - ai_sales_network

volumes:
  postgres_data:
  redis_data:
  qdrant_data:

networks:
  ai_sales_network:
    driver: bridge